services:
    postgres:
        container_name: url_shortener_postgres
        image: postgres:16.2-bullseye
        env_file:
            - .env
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: "postgres"
        networks:
            - internal
        volumes:
            - ./volumes/pgdata:/var/lib/postgresql/data
    
    redis:
        container_name: url_shortener_redis
        image: redis:alpine3.19
        env_file:
            - .env
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_DATABASES: 1
        networks:
            - internal
        volumes:
            - ./volumes/rsdata:/data

    app:
        container_name: url_shortener
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
            - redis
        networks:
            - internal
            - external

    nginx:
        container_name: nginx
        image: nginx:stable-perl
        working_dir: /app
        depends_on:
            - app
        networks:
            - external
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        links:
            - app
        ports:
            - 80:80

volumes:
    pgdata:
    rsdata:

networks:
    internal:
    external: