services:
    postgres:
        container_name: url_shortener_postgres
        image: postgres:16.3-alpine3.20
        env_file:
            - .env
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: "postgres"
        networks:
            - internal
        volumes:
            - ./volumes/pgdata:/var/lib/postgresql/data
    
    redis:
        container_name: url_shortener_redis
        image: redis:alpine3.20
        env_file:
            - .env
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_DATABASES: 1
        networks:
            - internal
        volumes:
            - ./volumes/rsdata:/data

    app:
        container_name: url_shortener
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
            - redis
        networks:
            - internal
        ports:
            - 80:80

volumes:
    pgdata:
    rsdata:

networks:
    internal: